name: Check New Places

on:
  workflow_dispatch:
  schedule:
    - cron: '6 8 * * *' # This schedules the action to run every day at 8am UTC which is 4am EDT

jobs:
  check_new_places:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python run.py
      env:
        GMAPS_API: ${{ secrets.GMAPS_API }}

    - name: Commit and push if it changed
      run: | 
        git config user.name "JonathanGrant"
        git config user.email "jonathanallengrant@gmail.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated places list at $timestamp" || exit 0
        git push https://${{ secrets.GH_TOKEN }}@github.com/JonathanGrant/GMapsDiscovery.git

